---
- name: install mesos packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - https://bintray.com/artifact/download/asteris/mantl-rpm/mesos-{{ mesos_version }}-{{ mesos_iteration }}.x86_64.rpm
    - cyrus-sasl-md5
  tags:
    - mesos
    - bootstrap
    - packaging

- name: ensure consul.d is present
  sudo: yes
  file:
    path: "{{ consul_dir }}"
    state: directory
  tags:
    - mesos

- include: leader.yml
  when: mesos_mode == "leader" or mesos_mode == "mixed"

- include: follower.yml
  when: mesos_mode == "follower" or mesos_mode == "mixed"
