---
- name: install glusterfs repo package
  sudo: yes
  yum:
    name: "{{ glusterfs_repo_package }}"
    state: present
  tags:
    - glusterfs
    - packaging

- include: server.yml
  when: glusterfs_mode == "server"

- include: client.yml
