---
- name: install consul-template
  sudo: yes
  yum:
    name: consul-template-0.12.2
    state: present
  tags:
    - consul-template
    - bootstrap
    - packaging

# disable when packaging
- name: disable consul-template
  sudo: yes
  service:
    name: consul-template
    enabled: no
  tags:
    - consul-template
    - packaging

- name: configure consul-template
  sudo: yes
  template:
    src: consul.cfg.j2
    dest: /etc/consul-template/config.d/consul.hcl
  notify:
    - reload consul-template
  tags:
    - consul-template

- name: enable consul-template
  sudo: yes
  service:
    name: consul-template
    enabled: yes
    state: started
  tags:
    - consul-template
