---
- name: install vault
  sudo: yes
  yum:
    name: "https://bintray.com/artifact/download/asteris/mantl-rpm/vault-0.4.1-1.x86_64.rpm"
    state: present
  tags:
    - vault
    - bootstrap
    - packaging

- name: configure vault
  sudo: yes
  template:
    src: vault.hcl.j2
    dest: /etc/vault/vault.hcl
  tags:
    - vault

- name: enable vault
  sudo: yes
  service:
    name: vault
    enabled: yes
    state: started
  tags:
    - vault

- name: wait for vault port
  wait_for:
    port: 8200
  tags:
    - vault

- include: bootstrap.yml
