---
- name: deploy root ca
  sudo: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
  with_items:
    - src: ssl/cacert.pem
      dest: /etc/pki/CA/ca.cert
    - src: ssl/cacert.pem
      dest: /etc/pki/ca-trust/source/anchors/cacert.pem
    - src: ssl/private/cakey.pem
      dest: /etc/pki/CA/ca.key
    - src: ssl/certs/host.cert.pem
      dest: /etc/pki/tls/certs/host.cert
    - src: ssl/private/host.key.pem
      dest: /etc/pki/tls/private/host.key
  notify:
    - update-ca-trust
